# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Python solar.py
# Created on: 2018-06-15 10:59:16.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Python solar <sol__Name_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
sol__Name_ = arcpy.GetParameterAsText(0)
if sol__Name_ == '#' or not sol__Name_:
    sol__Name_ = "D:\\PV_Model_Builder\\Arcmap\\try2_mb\\solar\\area solar\\sol_%Name%" # provide a default value if unspecified

# Local variables:
TIFF__2_ = "D:\\PV_Model_Builder\\Arcmap\\model\\raster\\ext\\TIFF"
Raster = "D:\\PV_Model_Builder\\Arcmap\\model\\raster\\ext\\TIFF\\Raster"
df__Name_ = "D:\\PV_Model_Builder\\Arcmap\\try2_mb\\solar\\diffuse\\df_%Name%"
di__Name_ = "D:\\PV_Model_Builder\\Arcmap\\try2_mb\\solar\\direct\\di_%Name%"
du__Name_ = "D:\\PV_Model_Builder\\Arcmap\\try2_mb\\solar\\duration\\du_%Name%"
Name = "Raster"

# Process: Iterate Rasters
arcpy.IterateRasters_mb(TIFF__2_, "*", "TIF", "RECURSIVE")

# Process: Area Solar Radiation
arcpy.gp.AreaSolarRadiation_sa(Raster, sol__Name_, "45", "200", "WholeYear   2018", "14", "0.5", "NOINTERVAL", "1", "FROM_DEM", "32", "8", "8", "UNIFORM_SKY", "0.3", "0.5", df__Name_, di__Name_, du__Name_)

