# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# model1.py
# Created on: 2018-05-16 00:07:56.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
b = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\b"
created_lasd_lasd = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\created lasd.lasd"
classified_las = created_lasd_lasd
DEM_based_on_actual_data = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\DEM based on actual data"
hillshade__3_ = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\raster\\hillshade"
solar = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\solar\\solar"
outputdirectradiation = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\outputdirectradiation"
outputdiffuseradiation = "C:\\Users\\Jingtian Zhang\\Documents\\ArcGIS\\Default1.gdb\\outputdiffuseradiation"
outputdirectduration = "C:\\Users\\Jingtian Zhang\\Documents\\ArcGIS\\Default1.gdb\\outputdirectduration"
aspect_shp = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\aspect\\aspect.shp"
Buildings = "Buildings"
cliped_shp = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\aspect\\cliped.shp"

# Process: Create LAS Dataset
arcpy.CreateLasDataset_management("'C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\b'", created_lasd_lasd, "RECURSION", "", "PROJCS['NAD_1983_StatePlane_Alaska_4_FIPS_5004_Feet',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',1640416.666666667],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-150.0],PARAMETER['Scale_Factor',0.9999],PARAMETER['Latitude_Of_Origin',54.0],UNIT['Foot_US',0.3048006096012192]]", "COMPUTE_STATS", "RELATIVE_PATHS", "NO_FILES")

# Process: Classify LAS Building
arcpy.ClassifyLasBuilding_3d(created_lasd_lasd, "6.56 Feet", "47.6 SquareFeet", "COMPUTE_STATS", "DEFAULT", "", "PROCESS_EXTENT")

# Process: LAS Dataset to Raster
arcpy.LasDatasetToRaster_conversion(created_lasd_lasd, DEM_based_on_actual_data, "ELEVATION", "BINNING AVERAGE NATURAL_NEIGHBOR", "FLOAT", "CELLSIZE", "1", "1")

# Process: Hillshade
arcpy.HillShade_3d(DEM_based_on_actual_data, hillshade__3_, "315", "45", "SHADOWS", "1")

# Process: Area Solar Radiation
arcpy.gp.AreaSolarRadiation_sa(DEM_based_on_actual_data, solar, "45", "200", "WholeYear   2018", "14", "1", "NOINTERVAL", "1", "FROM_DEM", "32", "8", "8", "UNIFORM_SKY", "0.3", "0.5", outputdirectradiation, outputdiffuseradiation, outputdirectduration)

# Process: Surface Aspect
arcpy.SurfaceAspect_3d(created_lasd_lasd, aspect_shp, "", "AspectCode", "0")

# Process: Clip
arcpy.Clip_analysis(aspect_shp, Buildings, cliped_shp, "6 Inches")

