# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# model_draft.py
# Created on: 2018-05-24 16:35:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
b = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\b"
created_lasd_lasd = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\created_lasd.lasd"
classified_las = created_lasd_lasd
DEM = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\DEM"
hillshade__3_ = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\raster\\hillshade"
direct = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\solar\\direct"
diffuse = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\solar\\diffuse"
directdur = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\solar\\directdur"
solar = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\solar\\solar"
Buildings__2_ = "Buildings"
mbextsolar = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\mbextsolar"
solartopoint_shp = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\solar\\solartopoint.shp"
mbtrimslope = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\mbtrimslope"
mbslope = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\slope\\mbslope"
mbextslope = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\mbextslope"
slopemask = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\slope\\slopemask"
slopetopoint_shp = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\slope\\slopetopoint.shp"
mbaspect = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\aspect\\mbaspect"
Buildings__3_ = "Buildings"
mbextaspect = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\mbextaspect"
mbtrimaspnf = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\mbtrimaspnf"
aspectmask = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\aspect\\aspectmask"
aspecttopoint_shp = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\aspect\\aspecttopoint.shp"
trimaspf = "C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\modelbuilderfiles\\aspect\\trimaspf"

# Set Geoprocessing environments
arcpy.env.newPrecision = "SINGLE"
arcpy.env.XYResolution = "0.3 Feet"
arcpy.env.scratchWorkspace = "C:\\Users\\Jingtian Zhang\\Documents\\ArcGIS\\Default1.gdb"
arcpy.env.compression = "LZ77"
arcpy.env.coincidentPoints = "MEAN"
arcpy.env.outputCoordinateSystem = ""
arcpy.env.rasterStatistics = "STATISTICS 1 1"
arcpy.env.transferDomains = "false"
arcpy.env.resamplingMethod = "NEAREST"
arcpy.env.snapRaster = ""
arcpy.env.projectCompare = "NONE"
arcpy.env.outputZFlag = "Same As Input"
arcpy.env.qualifiedFieldNames = "true"
arcpy.env.tileSize = "128 128"
arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
arcpy.env.extent = "DEFAULT"
arcpy.env.XYTolerance = "0.3 Feet"
arcpy.env.tinSaveVersion = "CURRENT"
arcpy.env.nodata = "NONE"
arcpy.env.cellSize = "MAXOF"
arcpy.env.outputZValue = ""
arcpy.env.geographicTransformations = ""
arcpy.env.ZResolution = ""
arcpy.env.mask = ""
arcpy.env.workspace = "C:\\Users\\Jingtian Zhang\\Documents\\ArcGIS\\Default1.gdb"
arcpy.env.derivedPrecision = "HIGHEST"
arcpy.env.ZTolerance = ""

# Process: Create LAS Dataset
arcpy.CreateLasDataset_management("'C:\\Users\\Jingtian Zhang\\Desktop\\PV Model Builder\\b'", created_lasd_lasd, "RECURSION", "", "PROJCS['NAD_1983_StatePlane_Alaska_4_FIPS_5004_Feet',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',1640416.666666667],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-150.0],PARAMETER['Scale_Factor',0.9999],PARAMETER['Latitude_Of_Origin',54.0],UNIT['Foot_US',0.3048006096012192]]", "COMPUTE_STATS", "RELATIVE_PATHS", "NO_FILES")

# Process: Classify LAS Building
arcpy.ClassifyLasBuilding_3d(created_lasd_lasd, "6.56 Feet", "47.6 SquareFeet", "COMPUTE_STATS", "DEFAULT", "", "PROCESS_EXTENT")

# Process: LAS Dataset to Raster
arcpy.LasDatasetToRaster_conversion(created_lasd_lasd, DEM, "ELEVATION", "BINNING AVERAGE NATURAL_NEIGHBOR", "FLOAT", "CELLSIZE", "1", "0.3048")

# Process: Hillshade
arcpy.HillShade_3d(DEM, hillshade__3_, "315", "45", "SHADOWS", "1")

# Process: Area Solar Radiation
arcpy.gp.AreaSolarRadiation_sa(DEM, solar, "61", "300", "MultiDays   2018    5  160", "14", "1", "NOINTERVAL", "1", "FROM_DEM", "32", "8", "8", "UNIFORM_SKY", "0.3", "0.5", direct, diffuse, directdur)

# Process: extractbybuildings3
arcpy.gp.ExtractByMask_sa(solar, Buildings__2_, mbextsolar)

# Process: Raster to Point
arcpy.RasterToPoint_conversion(mbextsolar, solartopoint_shp, "VALUE")

# Process: 35 angle
arcpy.gp.RasterCalculator_sa("\"%mbextslope (2)%\"<35", mbtrimslope)

# Process: Slope
arcpy.Slope_3d(DEM, mbslope, "DEGREE", "1")

# Process: extractbybuildings1
arcpy.gp.ExtractByMask_sa(mbslope, Buildings__2_, mbextslope)

# Process: smaller than 35
arcpy.gp.SetNull_sa(mbtrimslope, mbextslope, slopemask, "VALUE=1")

# Process: Raster to Point (2)
arcpy.RasterToPoint_conversion(slopemask, slopetopoint_shp, "VALUE")

# Process: Aspect
arcpy.Aspect_3d(DEM, mbaspect)

# Process: extractbybuildings2
arcpy.gp.ExtractByMask_sa(mbaspect, Buildings__3_, mbextaspect)

# Process: unflat
arcpy.gp.RasterCalculator_sa("((\"%mbextaspect%\" >= 112.5)&(\"%mbextaspect%\" <= 247.5))", mbtrimaspnf)

# Process: unflat_facesouth
arcpy.gp.SetNull_sa(mbtrimaspnf, mbextaspect, aspectmask, "VALUE=0")

# Process: Raster to Point (3)
arcpy.RasterToPoint_conversion(aspectmask, aspecttopoint_shp, "VALUE")

# Process: flat
arcpy.gp.RasterCalculator_sa("\"%mbextaspect%\"=-1", trimaspf)

